# Generated by Django 4.1.4 on 2023-01-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='categories',
            new_name='category',
        ),
    ]
